export const IPC = {
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_TOGGLE_MAXIMIZE: 'window:toggle-maximize',
  WINDOW_CLOSE: 'window:close',
  APP_GET_INFO: 'app:get-info',
  WORKSPACE_SELECT: 'workspace:select',
  WORKSPACE_LIST: 'workspace:list',
  FILE_READ: 'file:read',
  FILE_WRITE: 'file:write',
  FILE_CREATE: 'file:create',
  FILE_RENAME: 'file:rename',
  FILE_DUPLICATE: 'file:duplicate',
  FILE_REMOVE: 'file:remove',
  FILE_REVEAL: 'file:reveal',
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_SAVE_KEY: 'settings:save-key',
  SETTINGS_DELETE_KEY: 'settings:delete-key',
  SETTINGS_TEST_AI: 'settings:test-ai',
  AI_ANALYZE: 'ai:analyze',
  AI_CANCEL: 'ai:cancel',
  EXTERNAL_COPY_OPEN: 'external:copy-open',
  EXTERNAL_COPY: 'external:copy',
} as const;
